Adds PhotoPicketViewModelBuilderTests
SzymonMrozek/form pull request #2
Opened 2019-12-10 22:01 UTC by mateuszwagner

2019-12-10 22:02 UTC, mateuszwagner commented
Btw. I checked memory graph after opening&closing photo picker few times and seems like there are no memory leaks.

2019-12-12 09:34 UTC, SzymonMrozek requested changes

2019-12-12 09:34 UTC, SzymonMrozek commented on FormApproaching/Utils/Dependencies.swift
> +// sourcery: AutoMockable
This shouldn't be auto mock

2019-12-12 09:34 UTC, SzymonMrozek commented on FormApproaching/Utils/Dependencies.swift
> +// sourcery: AutoMockable
You shoud rather create some structure that contains all mock dependencies

2024-12-10 10:13 UTC, closed without merging